apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-postgres
  template:
    metadata:
      labels:
        app: tickets-postgres
    spec:
      # volumes:
      #   - name: auth-db
      #     persistentVolumeClaim:
      #       claimName: auth-postgres-pv-claim
      containers:
        - name: tickets-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432 # Exposes container port
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: tickets-postgres-config
          # volumeMounts:
          #   - mountPath: /var/lib/postgresql/data
          #     name: auth-db  

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-postgres-srv
spec:
  selector:
    app: tickets-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432

# apiVersion: v1
# kind: Service
# metadata:
#   name: ticket-postgres-node-srv
# spec:
#   type: NodePort
#   selector:
#     app: tickets-postgres
#   ports:
#     - name: db
#       protocol: TCP
#       port: 5432
#   externalIPs:
#     - 192.168.1.7