apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: orders-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: orders-postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-srv
spec:
  selector:
    app: orders-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432

# apiVersion: v1
# kind: Service
# metadata:
#   name: orders-postgres-node-srv
# spec:
#   type: NodePort
#   selector:
#     app: orders-postgres
#   ports:
#     - name: db
#       protocol: TCP
#       port: 5432
#   externalIPs:
#     - 192.168.1.7