apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-postgres
  template:
    metadata:
      labels:
        app: payments-postgres
    spec:
      containers:
        - name: payments-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - configMapRef:
                name: payments-postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: payments-postgres-srv
spec:
  selector:
    app: payments-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
