apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-postgres-pv-volume # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: auth-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany # ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pv-claim # Sets name of PVC
  labels:
    app: auth-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Sets volume size