apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: adriantepes/authv2
          #image: us.gcr.io/ticketing-dev-362117/auth
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: auth-postgres-srv
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: authadmin
            - name: DB_DATABASE
              value: authentication
            - name: DB_SYNC
              value: "true"
            - name: AUTH_HOST
              value: "0.0.0.0"
            - name: AUTH_PORT
              value: "3000"
            # - name: MONGO_URI
            #   value: 'mongodb://auth-mongo-srv:27017/auth'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
# ClusterIP: Exposición interna entre Nodos del cluster (comunicación entre sí).
# Si no colocas el type, de forma predeterminada K8s sabrá que es ClusterIP.
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-node-srv
# spec:
#   type: NodePort
#   selector:
#     app: auth
#   ports:
#     - name: auth
#       protocol: TCP
#       port: 3000
#   externalIPs:
#     - 192.168.1.7